### ISSUE TITLE
the whole code

### ISSUE THREAD

**Issue by liujiyaoFDU** [TopoXLab/TopoInteraction#1]
Thanks for your excellent work！

Could I ask you when will you public the whole code?  

Looking forward to your reply.

**Comment by Saumya-Gupta-26** [comment]
Hello, thank you for your question. I have already included the whole code. I have updated the README with links to the external backbone architectures that I used, as well as the datasets.

Essentially, the proposed method is a loss function that can be used with any backbone architecture. This repo contains the code for the loss function and how to call it.
