### ISSUE TITLE
dice

### ISSUE THREAD

**Issue by JAYCHOU2020** [TopoXLab/TopoInteraction#2]

**Comment by Saumya-Gupta-26** [comment]
Hello, the current code uses CrossEntropy with the critical_voxels_map.

If you want to use Dice loss instead, you can modify in the following way:

1) Replace CrossEntropy with Dice here: https://github.com/TopoXLab/TopoInteraction/blob/1bcb4676245c4840762564155fa00d378b3978d0/TI_Loss.py#L25

2) Also replace the usage of CrossEntropy with Dice here: https://github.com/TopoXLab/TopoInteraction/blob/1bcb4676245c4840762564155fa00d378b3978d0/TI_Loss.py#L137

**Comment by JAYCHOU2020** [comment]
> Hello, the current code uses CrossEntropy with the critical_voxels_map.
> 
> If you want to use Dice loss instead, you can modify in the following way:
> 
> 1. Replace CrossEntropy with Dice here: https://github.com/TopoXLab/TopoInteraction/blob/1bcb4676245c4840762564155fa00d378b3978d0/TI_Loss.py#L25
> 2. Also replace the usage of CrossEntropy with Dice here: https://github.com/TopoXLab/TopoInteraction/blob/1bcb4676245c4840762564155fa00d378b3978d0/TI_Loss.py#L137

Thank you for your answer.Yes I understand, but doesn't diceloss calculate a scalar? How does this apply to critical_voxels_map? Does pixel-by-pixel computing diceloss yield vectors of the same size 。

**Comment by Saumya-Gupta-26** [comment]
The logic is as follows:

1) Compute the critical_voxels_map
2) A = Multiply the prediction with critical_voxels_map 
3) B = Multiply the GT with critical_voxels_map 
4) Compute Dice score between A and B

**Comment by JAYCHOU2020** [comment]
> Reference in

Thank you very much for your patience in answering my confusion, I benefited a lot!

**Comment by JAYCHOU2020** [comment]
> The logic is as follows:
> 
> 1. Compute the critical_voxels_map
> 2. A = Multiply the prediction with critical_voxels_map
> 3. B = Multiply the GT with critical_voxels_map
> 4. Compute Dice score between A and B
Thank you very much for your patience in answering my confusion, I benefited a lot!
