### ISSUE TITLE
TILoss value

### ISSUE THREAD

**Issue by JAYCHOU2020** [TopoXLab/TopoInteraction#4]
Hello author, thank you for your great work. I printed out the TILoss value when I was training with tiloss. I found that the tiloss value would be learned from the beginning with each epoch. It is not learned and updated throughout the training process like segmentation loss. Is something wrong with my code? Or is this a normal phenomenon. Looking forward to your answer

**Comment by Saumya-Gupta-26** [comment]
Hi, can you post the print logs? Ideally both the segmentation loss and TILoss keep decreasing through the epochs. I am a bit occupied for the next 10 days, but will be more available to help soon.

**Comment by JAYCHOU2020** [comment]
> Hi, can you post the print logs? Ideally both the segmentation loss and TILoss keep decreasing through the epochs. I am a bit occupied for the next 10 days, but will be more available to help soon.

Thank you for your reply. Can I add your contact information or email you？

**Comment by Saumya-Gupta-26** [comment]
sure, my email is saumgupta@cs.stonybrook.edu
